### ISSUE TITLE
I cannot get the synonyms to pop-up when double-clicking

### ISSUE THREAD

**Issue by goldwinde** [scitronboy/simply-synonyms#19]
I just a Grammarly response, but no Simply-Synonyms response. I am on a Mac using your Chrome extension.

See attached.  
![0simply](https://user-images.githubusercontent.com/95254609/143950811-9e2b3f2c-1a11-4494-96fe-abdeb19c66f1.png)

**Comment by bashbaugh** [comment]
Hmm, which website is this? And are you trying to get the definition, or synonyms? 

The current version is very buggy. A new release is coming within a few months that should fix many issues - you can join the waitlist at https://simplysynonyms.com if you want.

**Comment by goldwinde** [comment]
The website is AskDwightHow.org.

 

I want synonyms.

 

Okay.

 

With appreciation,

 

Dwight

 

***@***.***

AskDwightHow.org

 

Author of the book, "Courage: the Choice that Makes the Difference--Your Key to a Thousand Doors"

 

Life and Lifestyle coaching (since 1987)

    

1-206-923-9554 (USA Telephone)

1-206-457-2817 (USA text messaging)

86-153-9867-5712 (China Telephone)

AskDwightHow.org (website)

***@***.*** (email)

goldwindedwight (Skype)

goldwinde (Wechat)

 

http://amzn.to/2fhc1yU  (for my book recommendations)

https://amzn.to/2Jb4XUy (for my courage book)

http://www.askdwighthow.org/ (now mobile friendly)

 

From: Benjamin Ashbaugh ***@***.***>
Reply-To: Simply-Synonyms/extension ***@***.***>
Date: Tuesday, November 30, 2021 at 10:35 AM
To: Simply-Synonyms/extension ***@***.***>
Cc: Dwight GoldWinde ***@***.***>, Author ***@***.***>
Subject: Re: [Simply-Synonyms/extension] I cannot get the synonyms to pop-up when double-clicking (Issue #19)

 

Hmm, which website is this? And are you trying to get the definition, or synonyms?

The current version is very buggy. A new release is coming within a few months that should fix many issues - you can join the waitlist at https://simplysynonyms.com if you want.
